version: "3.8"

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    network_mode: host

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET_SG4RG}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_TOKEN}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
    restart: unless-stopped



  solargather_SG4RG:
    image: bohdans/sungather
    container_name: solargather_SG4RG
    restart: always
    volumes:
      - ./solargather_SG4RG/config.yaml:/config/config.yaml
      - ./solargather_SG4RG/logs:/logs
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8080:8080"  
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"

  solargather_SG12RG:
    image: bohdans/sungather
    container_name: solargather_SG12RG
    restart: always
    volumes:
      - ./solargather_SG12RG/config.yaml:/config/config.yaml
      - ./solargather_SG12RG/logs:/logs
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8081:8080"  
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"
