version: "3.8"

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    steps:
    - name: Fix permissions
      run: |
        if [ -d "/home/florian/actions-runner/_work/Solarserver/Solarserver" ]; then
          sudo chown -R $(whoami) /home/florian/actions-runner/_work/Solarserver/Solarserver
          sudo chmod -R +w /home/florian/actions-runner/_work/Solarserver/Solarserver
        fi
    container_name: homeassistant
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    network_mode: host

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_TOKEN}
    restart: unless-stopped



  solargather_SG4RG:
    image: bohdans/sungather
    container_name: solargather_SG4RG
    restart: always
    volumes:
      - ./solargather_SG4RG/config.yaml:/config/config.yaml
      - ./solargather_SG4RG/logs:/logs
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8080:8080"  
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"

  solargather_SG12RG:
    image: bohdans/sungather
    container_name: solargather_SG12RG
    restart: always
    volumes:
      - ./solargather_SG12RG/config.yaml:/config/config.yaml
      - ./solargather_SG12RG/logs:/logs
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8081:8080"  
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"
