name: Deploy SolarGather to Proxmox


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Setup Mosquitto Password
        run: |
          mkdir -p ./mosquitto/config
          touch ./mosquitto/config/password.txt
          docker run --rm -v $(pwd)/mosquitto/config:/mosquitto/config eclipse-mosquitto mosquitto_passwd -b /mosquitto/config/password.txt ${MQTT_USERNAME} ${MQTT_PASSWORD}
      - name: Set owner of working dir recurively (Linux)
        run: sudo chown -R $(whoami) .

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare config and deploy
        run: |
          chmod +x prepare-config-and-deploy.sh
          ./prepare-config-and-deploy.sh


