name: Deploy SolarGather to Proxmox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:


      # 2) Fix ownership so we can clean and overwrite everything
      - name: Fix workspace permissions
        if: runner.os == 'Linux'
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      # 1) Get your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 3) Generate Mosquitto password file
      - name: Setup Mosquitto Password
        env:
          MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
        run: |
          # make sure the config folder exists
          mkdir -p "$GITHUB_WORKSPACE/mosquitto/config"
          # generate a fresh password.txt (overwrite with -c + batch -b)
          docker run --rm \
            -v "$GITHUB_WORKSPACE/mosquitto/config:/mosquitto/config" \
            eclipse-mosquitto mosquitto_passwd -c -b \
              /mosquitto/config/password.txt \
              "$MQTT_USERNAME" "$MQTT_PASSWORD"

      # 4) Deploy your stack
      - name: Prepare config and deploy
        run: |
          chmod +x prepare-config-and-deploy.sh
          ./prepare-config-and-deploy.sh
