name: Deploy SolarGather to Proxmox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare config and deploy
        run: |
          chmod +x prepare-config-and-deploy.sh
          ./prepare-config-and-deploy.sh
